export const IMAGES = {
  PERFORMANCE_CARD_IMG_1: "/assets/dashboardImgs/performanceCardImg1.png",
  PERFORMANCE_CARD_IMG_2: "/assets/dashboardImgs/performanceCardImg2.png",
  PERFORMANCE_CARD_IMG_3: "/assets/dashboardImgs/performanceCardImg3.png",
  PERFORMANCE_CARD_IMG_4: "/assets/dashboardImgs/performanceCardImg4.png",
  PROFILE_IMG: "/assets/profileImg.png",
  NAVBAR_MAIN_LOGO: "/assets/navbarMainLogo.png",
  SERVICES_REQUIRED: "/assets/services/servicesRequired.png",
  YOUR_ORDER: "/assets/services/yourOrder.png",
  OIL_LEVEL: "/assets/services/oliLevel.png",
  STEERING: "/assets/services/steering.png",
  BRAKE_PADS: "/assets/services/brakePads.png",
  CAR: "/assets/assets/car.png",
  GRAPH: "/assets/assets/graph.png",
  GOOGLE_BTN: "/assets/auth/googleLogo.png",
  FACEBOOK_BTN: "/assets/auth/facebookLogo.png",
  CARCARDIMG1: "/assets/home/carImg1.png",
};
