import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import StoreProvider from "./providers/storeProvider";
import { ThemeProvider } from "@/context/themeProvider";
import { AuthProvider } from "./authProviders";
import { ToastContainer } from "react-toastify";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "Car Rental Mamagment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.className}  antialiased`}
        cz-shortcut-listen="true"
      >
        <ToastContainer />
        <StoreProvider>
          <AuthProvider>
            <ThemeProvider>{children}</ThemeProvider>
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
